### ISSUE TITLE
lodash is the largest part of my bundle

### ISSUE THREAD

**Issue by thekevinbrown** [Rcomian/bunyan-rotating-file-stream#34]
I'm wondering if you'd consider replacing usage of lodash with built in JS now that most of lodash's functionality is part of the core. Lodash is the largest part of the bundle we're deploying in a Node based service we install on Windows machines via an auto update mechanism. It feels weird to have the library itself come in at 38.8 kb, but then lodash at 219 kb when only small parts of it are actually being used.

![Screenshot 2023-06-21 at 3 52 59 pm](https://github.com/Rcomian/bunyan-rotating-file-stream/assets/1531750/d24e7a24-e1ba-441b-adb4-612a70441737)

Given that this is backend code, bundle size isn't everything, but I thought I'd open the discussion anyway and see if you'd consider changing your imports to specific function imports, or switching off of lodash altogether, as I'd be happy to help with a PR if so.

**Comment by Rcomian** [comment]
Yes, certainly up for that
