### ISSUE TITLE
Rotating gz files

### ISSUE THREAD

**Issue by i3fox** [Rcomian/bunyan-rotating-file-stream#4]
Hi,

I see a note in "Deleting old files" section:
... (excluding the .gz if you are compressing old files)

Why totalFiles do not work when is present gzip option?
There is an option to enable this?

Thanks

**Comment by Rcomian** [comment]
I think it might just be bad wording. You can use totalFiles and gzip options together.

That section is trying to describe what files are considered when deleting things. It does consider the .gz files, it just ignores the .gz when doing the match.

**Comment by i3fox** [comment]
For me it is interesting to have delete also with gz file extension.

I need to keep a historical deep a week but for the size I zip logger.

**Comment by Rcomian** [comment]
As I say, it should work.

Have you tried this and found it doesn't work?

**Comment by i3fox** [comment]
I tried but doesn't work.

totalFiles: 7,
gzip: true,
period: 1d

In the log directory I found nine gz files and not only seven files.

datalog.2016-04-17.log.gz
datalog.2016-04-18.log.gz
datalog.2016-04-19.log.gz
datalog.2016-04-20.log.gz
datalog.2016-04-21.log.gz
datalog.2016-04-22.log.gz
datalog.2016-04-23.log.gz
datalog.2016-04-24.log.gz
datalog.2016-04-25.log.gz
datalog.2016-04-26.log

**Comment by Rcomian** [comment]
Aha!

Thank you, I'll look at this tonight.

**Comment by Rcomian** [comment]
Oh that's interesting.
If you change your pathname to: 'datalog-%Y-%m-%d.log' it will work.

You'll need to rename or move the existing log files.

Using a dot '.' after datalog is confusing the filename parser somehow. I'll work on a fix for this.

**Comment by i3fox** [comment]
I tried and it will work.

Thanks for your speed to fix a problem.
