### ISSUE TITLE
Error while using with Next.js in standalone mode: Variable `filteredlogstats` is not defined.

### ISSUE THREAD

**Issue by rgembalik** [Rcomian/bunyan-rotating-file-stream#42]
I am using this lib with Next.js compiled into standalone chunks. This leads to an error

```
Variable filteredlogstats is not defined.
```

My understanding is, that this line causes the issue: https://github.com/Rcomian/bunyan-rotating-file-stream/blob/e0616ace04b3166dc2745bb890c8aaaaed0cc63f/lib/datestampedfileops.js#L95

Variable `filteredlogstats` is being created and assigned without `let`/`var`/`const` keyword. Quick and easy solution would be to add it to the file. 

Is my reasoning correct? Would it be ok if I drop-in a fix PR for it?

**Comment by Rcomian** [comment]
oh yes, certainly, good spot!
