### ISSUE TITLE
Error: Cannot assign to read only property 'path' when Options read from JSON file

### ISSUE THREAD

**Issue by vishalgakhare** [Rcomian/bunyan-rotating-file-stream#8]
**I have the JSON file configuration:**
"logging": {
    "infoLogStream": {
      "path": "./logs/Info.%m%d_%H%M_%N.log",
      "period": "1h",
      "totalFiles":720,
      "threshold": "5m",
      "level":"info"
    }
  }

**I create the Bunyan Logger and add bunyan-rotating-file-stream:**
this.log = bunyan.createLogger({
        "name": serviceName
        });

      this.log.addStream({
        stream: new RotatingFileStream(config.get("logging.infoLogStream"))
      });

**When I start the NodeJS Server, I get the error:**
/BizEvents/node_modules/bunyan-rotating-file-stream/index.js:19
    options.path = path.resolve(options.path);
                 ^

**_TypeError: Cannot assign to read only property 'path' of #<Object>_**

    at new RotatingFileStreamFactory (/Users/vishal/Repos/BizEvents/node_modules/bunyan-rotating-file-stream/index.js:19:18)
    at Object.init (/Users/vishal/Repos/BizEvents/app/logger.js:52:17)
    at Object.<anonymous> (/Users/vishal/Repos/BizEvents/app.js:12:8)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

It works fine when I comment the error line.

**Comment by Rcomian** [comment]
wonder if something has changed somewhere, can you tell me what version of node you're using?

**Comment by vishalgakhare** [comment]
node = v4.2.6
"bunyan-rotating-file-stream": "^1.6.0",

**Comment by Rcomian** [comment]
Looks like the issue was the the `config` npm module produces a configuration object that's immutable.

To work with this I'm making a simple copy of the options object. Although commenting out the problematic line works for you (and the line is of dubious utility anyway), I can't guarantee I'll remember that case in the future and it's hard to test for all cases of it.

Hope this helps.

**Comment by vishalgakhare** [comment]
Thanks @Rcomian !
Q1 - Just trying to understand the root cause - why the immutable config option object would not get assigned to the "path"? Isn;t it because the path is read only? The right side option assignment value could be mutable or immutable.

**Comment by Rcomian** [comment]
The pattern being used here is the `options` object is being generated with the `config` npm module. This module is quite good, and produces config objects that can't be modified, that's fine.

The `rotating file stream` hasn't seen this style of options object before, and I modify the inbound object with the assumption that I can do so safely. I add defaults and things and it's normally fine. But the object from the `config` module is immutable. This is a good idea, and I guess I really shouldn't be modifying objects I don't own.

So I'm making a copy of the object and modifying that as needed.
Which fixes the issue you're having and is safe for the future.

If you'd simply embedded the configuration in the code as an object directly, it would have worked fine. But I like the idea of immutable configs and might work to integrate them more tightly in the future.

**Comment by vishalgakhare** [comment]
I just understood your fixe and came to comment here. Your explanation is much better. Thanks!

**Comment by Rcomian** [comment]
Thanks for letting me know about this :+1:

**Comment by vishalgakhare** [comment]
And yes, it's working good now! :)
